// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6VhNSK-S98TH7ige3NtgunvQwLCDKopo',
    appId: '1:240175782632:web:510fc9b16415f3e88e075d',
    messagingSenderId: '240175782632',
    projectId: 'todo-app-b9831',
    authDomain: 'todo-app-b9831.firebaseapp.com',
    storageBucket: 'todo-app-b9831.firebasestorage.app',
    measurementId: 'G-7XZ89RDT9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxvo26uv5qr2tm1TlrCJ9MdbR5HSl5b8',
    appId: '1:240175782632:android:99b8213a4ca4db238e075d',
    messagingSenderId: '240175782632',
    projectId: 'todo-app-b9831',
    storageBucket: 'todo-app-b9831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAf1LlyAgNuv6jFnsSinjsmQLIZmqImO8',
    appId: '1:240175782632:ios:48359fef47fe8d0e8e075d',
    messagingSenderId: '240175782632',
    projectId: 'todo-app-b9831',
    storageBucket: 'todo-app-b9831.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAf1LlyAgNuv6jFnsSinjsmQLIZmqImO8',
    appId: '1:240175782632:ios:48359fef47fe8d0e8e075d',
    messagingSenderId: '240175782632',
    projectId: 'todo-app-b9831',
    storageBucket: 'todo-app-b9831.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6VhNSK-S98TH7ige3NtgunvQwLCDKopo',
    appId: '1:240175782632:web:2a0b2a644e2a33368e075d',
    messagingSenderId: '240175782632',
    projectId: 'todo-app-b9831',
    authDomain: 'todo-app-b9831.firebaseapp.com',
    storageBucket: 'todo-app-b9831.firebasestorage.app',
    measurementId: 'G-411Z7ZG7P2',
  );
}
